general:
  # Lista de simboluri pe care strategia activă le va verifica
  symbols_forex:
  - GBPUSD
  - USDCHF
  - USDCAD
  - USDJPY
  - EURGBP
  - AUDUSD
  - EURUSD
  
  # Setările generale ale contului
  daily_profit: 75.0
  daily_loss: -50.0
  risk_per_trade: 0.005 # 0.5% Risc per tranzacție
  max_position_lot: 0.3
  min_free_margin_ratio: 0.6
  deviation: 10
  session_hours: []
  max_drawdown: 0.2 # Drawdown-ul maxim general al contului

trailing:
  be_min_profit_pips: 40
  be_secured_pips: 5             
  step_pips: 5
  atr_multiplier: 3
  profit_lock_threshold_pips: 50
  profit_lock_guarantee_pips: 25

strategies:
  ema_rsi_scalper:
    enabled: true   
    magic_number_base: 19133000
    
    # Parametrii ficși (comuni) stabiliți în urma testării
    timeframe: 'M5'
    h1_ema_period: 50
    m5_atr_period: 14
    m5_rsi_period: 14

    # --- PARAMETRI SPECIFICI PER SIMBOL ---
    # Doar simbolurile setate pe 'enabled: true' aici vor rula.
    symbol_settings:
      EURUSD:
        enabled: true
        magic_number_offset: 1
        rr_target: 2.3605
        sl_atr_multiplier: 2.219
        rsi_oversold: 22
        rsi_overbought: 85

      GBPUSD:
        enabled: tru
        magic_number_offset: 2 
        rr_target: 3.4279
        sl_atr_multiplier: 2.3478
        rsi_oversold: 19
        rsi_overbought: 80

      USDCHF:
        enabled: true
        magic_number_offset: 3
        rr_target: 1.0560
        sl_atr_multiplier: 3.0641
        rsi_oversold: 19
        rsi_overbought: 84

      USDCAD:
        enabled: true
        magic_number_offset: 4
        rr_target: 1.1447
        sl_atr_multiplier: 3.048
        rsi_oversold: 15
        rsi_overbought: 83
        
      USDJPY:
        enabled: true
        magic_number_offset: 5
        rr_target: 3.2646
        sl_atr_multiplier: 4.1034
        rsi_oversold: 16
        rsi_overbought: 85

      EURGBP:
        enabled: false
        magic_number_offset: 6
        rr_target: 1.5
        sl_atr_multiplier: 2.0
        rsi_oversold: 30
        rsi_overbought: 70
        
      AUDUSD:
        enabled: true
        magic_number_offset: 7
        rr_target: 1.495
        sl_atr_multiplier: 1.2656
        rsi_oversold: 15
        rsi_overbought: 84
        
      NZDUSD:
        enabled: true
        magic_number_offset: 8
        rr_target: 1.1135
        sl_atr_multiplier: 1.756
        rsi_oversold: 17
        rsi_overbought: 85